### ISSUE TITLE
希望可以增加方法描述上参数描述点击小火箭描述信息赋值的功能

### ISSUE THREAD

**Issue by lizhenwei188** [dromara/fast-request#102]
## 建议/改进(Suggestion/improvement)
![image](https://user-images.githubusercontent.com/75909527/184611244-a5012e3c-1906-499c-a121-65c4f0672e8f.png)

**Comment by kings1990** [comment]
暂时用实体类代替，实体类+javadoc支持的

**Comment by kings1990** [comment]
2022.2.5支持
