### ISSUE TITLE
idea中添加cookie实际是无效的

### ISSUE THREAD

**Issue by wtgithub22** [dromara/fast-request#103]
### 当前使用版本(Current Version)
2022.2.3.1
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- 如下图，同样的接口在postman中添加同样的cookie是有效请求的，但是在插件中是无法请求成功的
![image](https://user-images.githubusercontent.com/109931403/185535891-4758c8b2-7aa5-41da-a5f8-abb3075d58c0.png)

![image](https://user-images.githubusercontent.com/109931403/185536486-1ce5df35-954b-4005-9520-220ee5f042d7.png)

### 报错信息(Error Message)
无

**Comment by flyKite1998** [comment]
这个bug还在吧  2022.2.8版本header添加cookie无效 postman成功

**Comment by kings1990** [comment]
请看一下是否开启了自动cookie，如果开了请关闭

**Comment by kings1990** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/8969637/202987108-dd722534-d4db-4d62-bfcb-51983cddbd04.png">

**Comment by flyKite1998** [comment]
![image](https://user-images.githubusercontent.com/59674006/202997136-95fbf822-a4f5-419d-91ac-705f8923dce9.png)
![image](https://user-images.githubusercontent.com/59674006/202997286-160636e2-6bbb-40dd-aa01-53949f7dfa91.png)
![image](https://user-images.githubusercontent.com/59674006/202997382-213dce1c-abf8-4789-b798-1ba768f10228.png)
没有覆盖掉，确实是无效

**Comment by kings1990** [comment]
>中文

模块级别的Cookie应该覆盖项目级别的cookie，这个bug下个版本修复


>English

Module level cookies should override project level cookies, this bug will be fixed in the next version

**Comment by kings1990** [comment]
Please update to 2022.2.9+

**Comment by flyKite1998** [comment]
发现一个问题 登录时header里有时有cookie有时没有 这是三次登录返回cookie结果 
![image](https://user-images.githubusercontent.com/59674006/211281276-20845db7-1ac4-4b0e-a060-b690cd1bcc1f.png)
![image](https://user-images.githubusercontent.com/59674006/211281309-9f075038-bc60-438f-80ab-356ba41821c2.png)
![image](https://user-images.githubusercontent.com/59674006/211281352-638e8869-5932-40ed-bab7-e38ca1431537.png)
postman没有这种问题
![image](https://user-images.githubusercontent.com/59674006/211282138-2a73be9e-3327-43ae-a64a-a1c7568fc3e1.png)

**Comment by kings1990** [comment]
麻烦提供一下cookie那一串完整字符串，我这边测试一下

**Comment by flyKite1998** [comment]
JSESSIONID=23D48DFA37CBF21458B78EE8F87DE2CD  这是shiro登录后返回的  还有个问题就是 项目启动后 点击登录 再调用其他接口 会提示我登陆状态过期 需要我再点击登录之后  才能调用其他接口

**Comment by kings1990** [comment]
看看能不能在前置脚本里面写个逻辑 塞这个JSESSIONID
