### ISSUE TITLE
url params输入框建议

### ISSUE THREAD

**Issue by whyhhh** [dromara/fast-request#109]
输入法为英文或者输入数字，可以直接添加到输入框
但使用键盘切换输入框时，输入法为中文时，无法输入，，建议改进一下
![1662000133689_68F587D5-BDDB-4152-AD82-ACE075F6107E](https://user-images.githubusercontent.com/41336760/187821404-e7011bf5-7d67-42da-92f0-57e7e289936c.png)

**Comment by kings1990** [comment]
没理解
<img width="649" alt="image" src="https://user-images.githubusercontent.com/8969637/187822181-7f06addd-ebe5-4a56-8b7a-f2919ea82431.png">

**Comment by whyhhh** [comment]
> 没理解 <img alt="图片" width="649" src="https://user-images.githubusercontent.com/8969637/187822181-7f06addd-ebe5-4a56-8b7a-f2919ea82431.png">

![fastquest反馈](https://user-images.githubusercontent.com/41336760/191910555-7492d79b-4934-4345-8e1d-cb068e8aecc6.gif)

**Comment by kings1990** [comment]
得聚焦一下窗口
