### ISSUE TITLE
合理性建议

### ISSUE THREAD

**Issue by w-a-n-g-s-h-u-n** [dromara/fast-request#112]
## 建议/改进(Suggestion/improvement)
1.希望支持脚本分API设置，目前好像只有一个全局的
2.希望支持查看原始request

**Comment by kings1990** [comment]
第一点你可以在这边加脚本
<img width="722" alt="image" src="https://user-images.githubusercontent.com/8969637/188251698-3f787019-aaa4-4c9c-bf74-facdc5f0c5c2.png">

第二点2022.2.5支持console打印能满足了

**Comment by w-a-n-g-s-h-u-n** [comment]
单独API加的脚本 保存不了
原因不明
