### ISSUE TITLE
接口参数value值希望可以针对项目全局配置

### ISSUE THREAD

**Issue by W-Boo** [dromara/fast-request#123]
## 建议/改进
[eg:针对参数的实体类可以自定义设置值，对某些接口测试时，不用每次需要手动输入value值。不用实时读取，能够设置一个默认的就够了
[![vTDS54.png](https://s1.ax1x.com/2022/09/05/vTDS54.png)](https://imgse.com/i/vTDS54)

**Comment by kings1990** [comment]
使用swagger默认值注解
https://dromara.gitee.io/fast-request/guide/feature.html#swagger%E9%BB%98%E8%AE%A4%E5%80%BC%E8%A7%A3%E6%9E%90%E6%94%AF%E6%8C%81
