### ISSUE TITLE
前置脚本执行后，本次请求报错，后置脚本就不会执行

### ISSUE THREAD

**Issue by floatinghua** [dromara/fast-request#125]
## 建议/改进(Suggestion/improvement)
希望能在后置脚本中能根据响应码继续执行后续的脚本操作
下图是不会执行remove操作的
![微信图片_20220906115023](https://user-images.githubusercontent.com/38682071/188543293-6b7d479c-3ae1-4a83-a9ee-2fe3f24006f6.jpg)
根据响应码判断需要继续执行下面的操作
![image](https://user-images.githubusercontent.com/38682071/188543369-e873020d-3270-4efc-bdbb-7f98cc646cab.png)

**Comment by kings1990** [comment]
update to 2022.2.5+
