### ISSUE TITLE
工具类图标自定义颜色在每次打开idea时不会改变

### ISSUE THREAD

**Issue by W-Boo** [dromara/fast-request#126]
idea2022.2版本，插件最新版，设置了工具类图标颜色，每次打开idea，图标颜色还是上一次设置的颜色，点一下图标才会变色

![1662449497049](https://user-images.githubusercontent.com/75486440/188574610-c82aa2c7-8af1-4336-ae19-c9d27611c06f.jpg)
<img width="124" alt="Snipaste_2022-09-06_15-31-57" src="https://user-images.githubusercontent.com/75486440/188574673-39788f54-fee2-4003-85a4-ba71b80e6d1b.png">
<img width="277" alt="Snipaste_2022-09-06_15-32-19" src="https://user-images.githubusercontent.com/75486440/188574683-4665c978-02f1-46e2-b050-d7866028ff7a.png">

**Comment by kings1990** [comment]
<img width="404" alt="image" src="https://user-images.githubusercontent.com/8969637/188766179-77ae7c61-3b95-49fc-aefa-20f8cfb69264.png">
重启项目也不行么

**Comment by kings1990** [comment]
目前首次打开会出现默认图标，受到jb默认加载机制的影响 没法处理
