### ISSUE TITLE
加载速度优化

### ISSUE THREAD

**Issue by ttbadr** [dromara/fast-request#130]
### 当前使用版本(Current Version)
idea UL 2022.2.1
插件版本 2022.2.4.1

### 重现步骤(Repeat steps)
第一次点击图标大概要十秒左右界面才加载出来，后面点击就很快了，建议优化一下第一次加载速度

**Comment by kings1990** [comment]
第一次点击图标 点的是哪边的图标 截个图

**Comment by ttbadr** [comment]
> 第一次点击图标 点的是哪边的图标 截个图

![image](https://user-images.githubusercontent.com/3127447/190300818-988e3967-f45f-4982-8441-6b85b2cc5c86.png)

**Comment by kings1990** [comment]
我这边秒开,是不是你刚启动还有很多东西还在加载

**Comment by ttbadr** [comment]
> 我这边秒开,是不是你刚启动还有很多东西还在加载

不是刚启动就点开的， 是启动很久了才点开，我另外一台电脑就没这个问题，不知道两者有什么区别

**Comment by kings1990** [comment]
有可能是电脑配置的问题吧，不好复现
