### ISSUE TITLE
配置导出支持

### ISSUE THREAD

**Issue by SeSiTing** [dromara/fast-request#133]
## 建议/改进(Suggestion/improvement)
eg:希望fast request的配置可以支持导出
![飞书20220919-100234](https://user-images.githubusercontent.com/44688404/190939153-db5a2468-ea0f-4eb8-b4f4-ea1d1b923781.png)

**Comment by kings1990** [comment]
建议使用 [项目级别域名配置](https://dromara.gitee.io/fast-request/guide/features/projectLevelDomainConfig.html)
