### ISSUE TITLE
Navigate 加上注释显示

### ISSUE THREAD

**Issue by fuuqiu** [dromara/fast-request#135]
## 建议/改进(Suggestion/improvement)
eg:希望支持xx类型的解析(eg:hope to support parsing of type XX)

**核心诉求**：
**P0**:Navigate 加上接口注释。如果UI考虑的话，可在全局配置中按需打开，默认关闭状态。

_以下个人建议：_

**P4**:String的图标是一个 A  调整为 S 是不是更好呢？
**P4**:另外发现控制器上的 @Api(tags = “文件管理”） 注解不识别，在接口保存分组时以类名命名，支持注解分组就好了

**Comment by kings1990** [comment]
暂时显示API方法的描述

**Comment by kings1990** [comment]
update to 2022.2.6+
