### ISSUE TITLE
建议优化一下，安装完这个插件，每次打开项目idea都会冻结一分钟左右

### ISSUE THREAD

**Issue by meiMingle** [dromara/fast-request#136]
### 当前使用版本(Current Version)
idea2022.2.2
Restful Fast Request 2022.2.5.2

### 重现步骤(Repeat steps)
- maven模块240+，Controller类300+，api 500+

### 报错信息(Error Message)
一分钟左右idea冻结无法进行任何操作，没有报错信息

**Comment by kings1990** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/8969637/191879049-c040328b-e8cf-480e-bea7-2610931d9e56.png">

<img width="695" alt="image" src="https://user-images.githubusercontent.com/8969637/191879097-08ac7829-d0ee-4e29-916e-b8cc13543ae2.png">

不会吧你是不是索引的问题

**Comment by meiMingle** [comment]
![image](https://user-images.githubusercontent.com/39942874/191883029-59cf2ea3-9731-49f7-9cb1-03a07f337d6d.png)
从这里的结果来看耗时并不长，但是冻结确实是发生在这个插件安装之后，更具体的发生时机是打开项目后在“Scaning files to index”进度条跑满之后

**Comment by meiMingle** [comment]
从idea的冻结日志来看，似乎卡在了插件进行的网络请求
![image](https://user-images.githubusercontent.com/39942874/191885506-99af12ae-6d27-42df-9edd-7dc7d7c8083c.png)

**Comment by kings1990** [comment]
进群细聊一下

**Comment by kings1990** [comment]
update to 2022.2.6+
