### ISSUE TITLE
希望增加对kotlin接口的支持

### ISSUE THREAD

**Issue by LambdaV5** [dromara/fast-request#15]
希望增加对kotlin接口的支持，目前kotlin写的接口不能识别

**Comment by kings1990** [comment]
求支援

**Comment by GoldSubmarine** [comment]
可以参考 https://github.com/GoldSubmarine/RestfulHelper
@kings1990 

如果你只有搜索需求的话，可以直接使用上述插件 @LambdaV5

**Comment by kings1990** [comment]
@GoldSubmarine  FastRequest搜索功能下个功能有了，参考了RestfulHelper的kotlin代码，同时RestfulHelper有个bug，点那个more出来的就有问题(我知道怎么解决)，希望线下可以对接一下，qq：963987632

**Comment by kings1990** [comment]
2022.1.7支持kotlin+spring系列
