### ISSUE TITLE
界面优化建议

### ISSUE THREAD

**Issue by guzzhao** [dromara/fast-request#150]
## 建议/改进(Suggestion/improvement)

1. 把send发送请求按钮放到url旁边,或者把状态码变成按钮可以点击发送请求

2. 自动生成参数功能增加 只添加key不添加值并且生成后不打勾

**Comment by kings1990** [comment]
2022.2.6版本可以一键清除参数，发送请求可以用快捷键触发，第一个tab所有的关键按钮都是有快捷键的

[https://dromara.gitee.io/fast-request/guide/getstarted/shortcut.html](https://dromara.gitee.io/fast-request/guide/getstarted/shortcut.html)
