### ISSUE TITLE
批量保存APIs

### ISSUE THREAD

**Issue by HwwwwwLemon** [dromara/fast-request#158]
## 建议/改进(Suggestion/improvement)
如题，API需要导出到Postman里面，当前是单个API保存，一个Controller里面N个API一个一个去保存属实有点累。
希望后期出一个可以一键保存一整个Controller中API的功能，至于参数是否自动填充随设置，如过有调试过就取历史请求的参数。

**Comment by kings1990** [comment]
这个后期不会支持的哦
