### ISSUE TITLE
建议增加对smart-doc中@mock和@ignore等通用自定义注释的支持

### ISSUE THREAD

**Issue by WangYajun39** [dromara/fast-request#159]
## 建议/改进(Suggestion/improvement)
建议增加对smart-doc中@mock和@ignoreParams等通用自定义注释的支持
- smart-doc文档地址：https://smart-doc-group.github.io/#/zh-cn/start/javadoc
- @mock用于在对象基本类型字段设置自定义值
- @ignoreParams忽略字段

**Comment by kings1990** [comment]
https://api-buddy.com/guide/faq.html#s-%E8%A7%A3%E6%9E%90%E5%A6%82%E4%BD%95%E5%BF%BD%E7%95%A5%E6%9F%90%E4%B8%AA%E5%AD%97%E6%AE%B5
