### ISSUE TITLE
Headers配置无法保存，并且点击清空按钮Headers配置也没有消失

### ISSUE THREAD

**Issue by meiMingle** [dromara/fast-request#167]
### 当前使用版本(Current Version)
Restful Fast Request 2022.2.6, idea 2022.2.3
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
1.通过Controller方法前面的快捷按钮生成API配置
2.在Headers下新建，如 Content-type: application/json;charset=GBK
3.点保存，然后点清空，这时候Headers配置没有消失
4.点“-”把Headers配置移除后，在APIs下双击刚刚创建的API，Headers配置还是空的

**Comment by kings1990** [comment]
清空不清header
