### ISSUE TITLE
Headers配置取消勾选后又自动恢复勾选

### ISSUE THREAD

**Issue by meiMingle** [dromara/fast-request#168]
### 当前使用版本(Current Version)
Restful Fast Request 2022.2.6, idea 2022.2.3
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
1.通过Controller方法前面的快捷按钮生成API配置
2.在Headers下新建，如 Content-type: application/json;charset=GBK，并取消勾选
![image](https://user-images.githubusercontent.com/39942874/197918359-7a210094-233e-4ebd-971e-3a1ce04d6953.png)

3.点击‘Send’按钮，这时候Header没生效，并且这时候查看Header配置已经自动勾选
![image](https://user-images.githubusercontent.com/39942874/197917932-3f87f854-acb0-446b-beb1-2d3548f34ccf.png)
![image](https://user-images.githubusercontent.com/39942874/197918661-a5d1bfd2-6e3c-4923-abaf-f05076dd98ef.png)

4.再次点击‘Send’按钮，Header配置也生效了
![image](https://user-images.githubusercontent.com/39942874/197918919-7c5d1369-bc1b-4be9-a4f9-de5872cc4f74.png)

**Comment by kings1990** [comment]
update to 2022.2.7
