### ISSUE TITLE
给每个API配置独立的代理

### ISSUE THREAD

**Issue by meiMingle** [dromara/fast-request#169]
## 建议/改进(Suggestion/improvement)
希望可以给API设置独立的代理，就像这里提到的 [Allow http client requests to specify a proxy on a per-request basis](https://youtrack.jetbrains.com/issue/IDEA-293812)

**Comment by kings1990** [comment]
请对前置脚本request对象设置

例如
```
//new proxy
request.setProxy(proxy)

或者

request.setHttpProxy(host,port)
```
