### ISSUE TITLE
Headers配置的HeaderName 和 HeaderValue支持自动补全

### ISSUE THREAD

**Issue by meiMingle** [dromara/fast-request#170]
## 建议/改进(Suggestion/improvement)
idea自带的http脚本在设置请求头的时候有自动补全，很方便，建议这个能支持一下

![image](https://user-images.githubusercontent.com/39942874/197920315-d71aa8bb-2e02-4703-8063-85c8ff5a121d.png)
![image](https://user-images.githubusercontent.com/39942874/197920413-ab631aeb-891d-4f63-9266-3976b75dc269.png)

**Comment by kings1990** [comment]
这个目前做不了，控件不支持
