### ISSUE TITLE
建议增加xml、text、binary等body参数的支持

### ISSUE THREAD

**Issue by meiMingle** [dromara/fast-request#171]
## 建议/改进(Suggestion/improvement)
目前插件似乎仅支持json格式的body入参,非json格式的body参数就会报错并且没有发送请求
![image](https://user-images.githubusercontent.com/39942874/197922469-cf5fdc20-b567-4616-91c6-3936d0e8eacf.png)

![image](https://user-images.githubusercontent.com/39942874/197922135-485549ba-90d4-4c67-8f16-8ec9bb9e2640.png)

**Comment by kings1990** [comment]
2022.2.7支持通过快速公共请求头处理,同时修复bug

**Comment by kings1990** [comment]
update to 2022.2.7
