### ISSUE TITLE
如何激活插件？

### ISSUE THREAD

**Issue by zhaobinsir** [dromara/fast-request#180]
### 当前使用版本(Current Version)
2022.2.7
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
- 
![image](https://user-images.githubusercontent.com/28432309/201009552-40df0ec5-c63e-407f-a53e-8e415b0d7fc4.png)

**Comment by kings1990** [comment]
加入群里查看群教程或者参考在线的[文档](https://dromara.gitee.io/fast-request/guide/buy.html)
