### ISSUE TITLE
动画图标会分散注意力

### ISSUE THREAD

**Issue by CodeCooler** [dromara/fast-request#183]
### Current Version
2022.2.8

### Operation steps
新图标不断动画化。这非常分散注意力。请提供停止动画的选项。

<img width="232" alt="CleanShot 2022-11-15 at 10 14 50@2x" src="https://user-images.githubusercontent.com/7704047/201957904-b89ca78b-245c-4b20-9d4a-a5d9756da123.png">

- 

### Error Message

没有错误。

**Comment by kings1990** [comment]
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/8969637/202665703-420820ba-9ed5-4ac2-a6b9-280c79b9a2a5.png">



这个是支持配置化的，你可能没看[文档](https://dromara.gitee.io/fast-request/guide/features/makeIconMove.html)吧。

**Comment by kings1990** [comment]
麻烦插件主页的评论重新打个分

**Comment by kings1990** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/8969637/204744078-0d056e1e-19b8-41f8-8bf5-2659c5f84d41.png">
It supports close animation in global config in version 2022.2.9+.
