### ISSUE TITLE
如何试用2023.1.1版本

### ISSUE THREAD

**Issue by karl-chanel** [dromara/fast-request#200]
## Suggestion/improvement
eg:hope to support parsing of type XX

**Comment by kings1990** [comment]
[https://dromara.gitee.io/fast-request/guide/buy.html](https://dromara.gitee.io/fast-request/guide/buy.html) -> step0

**Comment by karl-chanel** [comment]
不，你理解错了，我说的不是试用正式版，我说的是试用你的开发版，就是没有上架那个plugin store的,你在文档里不是说可以免费试用开发版吗？我想说问一下怎么试用？

**Comment by kings1990** [comment]
试用的就是正式版，JetBrains所有的插件都是有这个选项的。试用指的是30天免费使用正式版
