### ISSUE TITLE
Using MappingJacksonValue let's the plugin crash

### ISSUE THREAD

**Issue by andrlange** [dromara/fast-request#203]
### Current Version
2023.1.1.2
### Operation steps
Example:
@GetMapping("/filtering")
    public MappingJacksonValue filtering() {

        SomeBean someBean = new SomeBean("value1", "value2", "value3");
        MappingJacksonValue mappingJacksonValue =
                new MappingJacksonValue(someBean);

        SimpleBeanPropertyFilter filter =
                SimpleBeanPropertyFilter.filterOutAllExcept("field1", "field3");

        FilterProvider filters = new SimpleFilterProvider().addFilter("SomeBeanFilter",
                filter);

        mappingJacksonValue.setFilters(filters);

        return mappingJacksonValue;
    }

### Error Message
hanging or crashing, the api uri is not provided to the plugin

**Comment by kings1990** [comment]
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/8969637/218352775-35525bfc-220f-4310-bd29-3797cfa0731e.png">
Hi, after I copied your code and tried it, it seems all work fine. Could you provide more detail?
