### ISSUE TITLE
Api Name 错误展示

### ISSUE THREAD

**Issue by SeSiTing** [dromara/fast-request#206]
### Current Version
最新版本
### Operation steps
- It's best to provide a image
![image](https://user-images.githubusercontent.com/44688404/222057459-1ede11bc-3eb6-4384-8c7b-55e59c70bb9c.png)

### Error Message
切换url 保存后总是会导致api name错乱

**Comment by kings1990** [comment]
切换url 操纵描述一下 是怎么个操作法

**Comment by SeSiTing** [comment]
1、依次保存4个api，详情是最后保存的
![image](https://user-images.githubusercontent.com/44688404/222315475-58d26695-a648-445c-95e7-c06865b5db42.png)
2、双击更新api，然后保存，此时名字就会被保存为详情
![image](https://user-images.githubusercontent.com/44688404/222315588-88be7ae6-5a16-42e6-aae4-0158948d7710.png)
