### ISSUE TITLE
发送json数据,会有拼接一个=号

### ISSUE THREAD

**Issue by iPisces77** [dromara/fast-request#210]
### Current Version
2023.1.2

### Operation steps
- It's best to provide a image
使用一个最小的springboot项目,原始字符串"json_3mwdw"会在传送到应用时,变为 %22json_3mwdw%22= 会添加一个等号
![image](https://user-images.githubusercontent.com/39837211/223728966-256f4053-7284-4295-93b7-4b1b01171533.png)

**Comment by kings1990** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/8969637/233517898-9053e105-e6bd-41ad-a601-7b384c00445a.png">
引号问题在2023.1.4修复，=问题在header上加Content-Type:application/json

**Comment by kings1990** [comment]
update to 2023.1.4+
