### ISSUE TITLE
调用接口有时候会一直读条没有发送出去请求

### ISSUE THREAD

**Issue by bankuaizhuan1** [dromara/fast-request#211]
插件版本2023.1.2
场景： 点击发送请求，有时候会一直读条，发不出去请求，点击停止再次发送还是一样情况，这时候如果使用postman调用一次，那么插件立马就给调用成功了，不然就需要等4，5分钟
![image](https://user-images.githubusercontent.com/73813723/223959536-2a96d417-cae0-4224-bd78-807364c45090.png)
read timed out 是等待了4.5分钟才发送出去
复现：不稳定触发，有时候上一次不行下一次就好了，反正就是debug状态，然后一直调接口

**Comment by kings1990** [comment]
应该是服务端的问题吧，全局配置可以设置一下超时时间
