### ISSUE TITLE
部分BUG与使用建议

### ISSUE THREAD

**Issue by fwnan** [dromara/fast-request#233]
## 版本信息
IDEA版本: 2023.1 (Build #IU-231.8109.175, built on March 28, 2023)
插件版本: 2023.1.3.2

## 建议
1.图标过于冗杂, 建议有些图标可以整合在一个图标下拉栏目下.
![image](https://user-images.githubusercontent.com/71653989/233530083-da2387a4-afbb-4de7-af93-a65efb5f683d.png)
如Window和FAQ完全没必要占位置.   边框不够大, 还会导致前面图标被隐藏, 或许可以把Navigate改成Nav, 减少长度占用?

2.希望可以自行调整Navigate/API/Request等栏目的位置.

3.Navigate目前的功能只有定位, 希望可以在该栏目增加如下功能:
   1.点击请求时, 默认以项目配置的端口以及本地路径, 可以就地进行REST请求, 无需定位后再点击图标跳转到Request发起请求.
   2.可以同时选中多个请求路径, 右键一键添加到APIs, 默认域名以及端口以本地识别为主.
  
## BUG
在我当前的IDEA版本, 插件的API搜索, 会导致IDEA本身自带的搜索框样式更改.
![image](https://user-images.githubusercontent.com/71653989/233532133-5ecc78f6-7405-4515-b786-75f97a185ac9.png)
IDEA原有样式如下, 这边只希望在此基础上增加一个FastRequest栏目, 不要影响原有逻辑.
![image](https://user-images.githubusercontent.com/71653989/233532268-d0a1b1f7-ee53-4c8c-b88b-d05af533876d.png)

**Comment by kings1990** [comment]
搜索出现样式错乱试着预切换一下主题就好了

**Comment by fwnan** [comment]
我的就是Light主题, 样式错乱问题还是存在. 不启用插件就是正常样式, 启用后就会导致搜索框样式变宽被挤占, 没法一眼看到当前用什么方式进行检索. 这个是比较麻烦的事.
![image](https://user-images.githubusercontent.com/71653989/233833011-14682d28-0d3a-4c3b-8195-65eb54c466d1.png)

**Comment by kings1990** [comment]
预切换一下，鼠标在别的主题上浮一下再切回来

**Comment by kings1990** [comment]
![image](https://user-images.githubusercontent.com/8969637/234150397-5f733ee7-8864-4237-bea7-ce20b02e0251.png)
