### ISSUE TITLE
插件会自动在当前项目根目录创建.fastRequest文件夹

### ISSUE THREAD

**Issue by FoundAdd** [dromara/fast-request#236]
## Suggestion/improvement
如标题所述，不知道是最近的哪个版本更新后，每次启动项目就会自动在根目录生成.fastRequest目录，即使手动删除了也会重新生成。
我大概能猜到这个目录是做什么用的，但是如果可以的话希望能在插件配置中自己选择这个目录的生成路径，比如放在.vscode、.idea路径下。
![image](https://user-images.githubusercontent.com/58539321/236751949-eebcb358-6268-49f0-8302-4ed8e0cc51ee.png)

**Comment by kings1990** [comment]
设计如此，可以利用这边的文件做到api共享
