### ISSUE TITLE
侧边栏logo的一个疑问

### ISSUE THREAD

**Issue by karanokyoukai** [dromara/fast-request#242]
虽然是个不算问题的问题，这个logo的颜色有地方可以设置吗？
希望可以自定义颜色，可以和边栏其他icon的样式统一
这个问题自从换新logo后纠结了几个月了
![image](https://github.com/dromara/fast-request/assets/41668004/6475150f-3d9f-4347-b18d-f1a4ba8c0164)

**Comment by kings1990** [comment]
<img width="881" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/9662ec95-3223-4fd1-98cc-45d49ec6d870">

**Comment by karanokyoukai** [comment]
感谢🥳

**Comment by kings1990** [comment]
这边不需要纠结，有的插件也是彩色的
