### ISSUE TITLE
使用 Gradle 进行自动域名配置的时候生成的域名总是以 `.main` 结尾但使用 Maven 构建就不会

### ISSUE THREAD

**Issue by Cola0502windows** [dromara/fast-request#243]
# 版本信息

IDEA 版本： IntelliJ IDEA 2023.1.1

插件版本：2023.1.6

# 疑问

> 你好 Kings1990 我是一名大二学生，我刚接触到这款插件，可能对一些细节不熟悉，我也查阅了官方文档
> 
> 但还是没弄好，就是我有一个疑问，当我使用 Gradle 构建 SpringBoot 工程的时候我直接点击 Controller 
> 
> 中请求 API 的图标进行自动域名配置的时候生成的域名总是以 `.main` 结尾但使用 Maven 构建就不会，请问这是为什么呢？

# 最小复现

> 没配置前

   ![](https://cola-jinzhong-picgo-1311841992.cos.ap-beijing.myqcloud.com/20230525025715.png)
> 点击图标

   ![](https://cola-jinzhong-picgo-1311841992.cos.ap-beijing.myqcloud.com/20230525025436.png)

**Comment by kings1990** [comment]
应该是项目结构的问题，正常来说应该是demo，可能你的项目设置吧main搞成了module
<img width="1460" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/2e2af484-401a-4d19-8cb9-1ff45729b026">
<img width="438" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/5b72b4cf-6f68-4672-9a77-407a3bdc47e5">

**Comment by kings1990** [comment]
叫胜哥就行了，哈哈哈

**Comment by kings1990** [comment]
<img width="725" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/40eedad4-bc8c-4342-8b06-6307fa68bda4">

先这么处理 
1.找到Project structure
2.选择Modules
3.删除Modules下方的src和test
4.右侧选择java或者kotlin文件夹->Make as Sources
4.右侧选择test文件夹->Make as Tests

这个是因为Gradle项目创建的时候默认把src和test认为是module了

也可以参考这边的[配置](https://youtrack.jetbrains.com/issue/IDEA-224360/Fine-tuning-IDEA-module-configuration-for-source-sets)

**Comment by kings1990** [comment]
Upgrade to 2023.1.7
