### ISSUE TITLE
导出到

### ISSUE THREAD

**Issue by FuGuiLiu** [dromara/fast-request#251]
### 通过导出postman配置导出的url路径有点问题

![image](https://github.com/dromara/fast-request/assets/63985387/fdd50b44-db57-4bb1-9502-2beb7b25f6e2)

这些C盘什么之类的路径是在哪里加上的

**Comment by kings1990** [comment]
使用 Postman 同步
[https://api-buddy.cn/guide/features/postmanSync.html](https://api-buddy.cn/guide/features/postmanSync.html)

**Comment by FuGuiLiu** [comment]
感谢
