### ISSUE TITLE
curl导入失败问题

### ISSUE THREAD

**Issue by fish-kings** [dromara/fast-request#253]
### Current Version
最新版本
### Operation steps
- It's best to provide a image
curl 导入出现问题 
![image](https://github.com/dromara/fast-request/assets/67667211/e88e17ca-5ca4-443f-bef2-539226c86210)

具体curl格式如下
curl 'http://127.0.0.1:8310/mobile/overEducationTrainInfo?levelCode=&trainType=&startDate=2023-05-21&endDate=2023-07-21&&&likeParam=' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://127.0.0.1' \
  -H 'Referer: http://127.0.0.1/' \
  -H 'User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1' \
  --compressed \
  --insecure

而且 导入失败后 再点击对应接口的请求图标 没反应
![image](https://github.com/dromara/fast-request/assets/67667211/fcd2fdb6-2b64-4fd3-9f4d-a213e0205408)
 还有就是参数提取问题
<img width="483" alt="image" src="https://github.com/dromara/fast-request/assets/67667211/899824f2-f840-478f-b0cf-e93076f139c9">
get请求 curl 导入，有多个同名参数，但是在发送请求时只能提取到第一个

**Comment by kings1990** [comment]
update to 2023.1.7
