### ISSUE TITLE
Incorrect case for static params

### ISSUE THREAD

**Issue by diroxx** [dromara/fast-request#255]
### Current Version
2023.1.6
### Operation steps
Request parameters that are static, aren't parsed and are just taken as raw string value.
I.E. 
```
Public static final String STATIC_STRING = "staticString";
@GetMapping(path = "/path")
public String getAString(@RequestParam(STATIC_STRING) final String staticString)
```
Parameter staticString key will be STATIC_STRING, instead of staticString, which will not work as parameters are case-sensitive.

**Comment by diroxx** [comment]
Addition: 
Similiar issue with Path Params.
```
public static final String PATH_PARAM = "pathParam";
@GetMapping(path="/" + PATH_PARAM )
public String getAString(@PathVariable(URL_PARAM)) final String pathParam)
```
Path parameter key will be PATH_PARAM, instead of pathParam and thus the url will contain the placeholder parameter and will not work.

**Comment by kings1990** [comment]
![fixparam](https://github.com/dromara/fast-request/assets/8969637/ded6769d-d485-47c1-92f0-e553fa02295d)

@diroxx Thanks for your feedback. I will fix this problem in the next plugin version `2023.1.7`

**Comment by diroxx** [comment]
Thanks!
