### ISSUE TITLE
无法删除保存的API

### ISSUE THREAD

**Issue by AWeiIsCoding** [dromara/fast-request#257]
### Current Version
IDEA 2021.2.2
fast-request 2023.1.7

### Operation steps
- It's best to provide a image
保存API后，点击delete无反应，无法删除该API。
![image](https://github.com/dromara/fast-request/assets/90399609/ce435dad-bcd4-44fe-a4d6-3ba2d10c2821)

### Error Message
没有错误信息

**Comment by kings1990** [comment]
你删除的是api还是controller，麻烦提供一下.fastRequest目录下的那几个跟你删除的controller相关的文件，谢谢

**Comment by AWeiIsCoding** [comment]
抱歉，我没有描述清楚，我删除的是controller。
这是模块名字目录下的`directory.json`文件。
`{
	"description":"",
	"directory":"/.fastRequest/collections/ROOT~service_cmn",
	"filePath":"/.fastRequest/collections/ROOT~service_cmn~",
	"name":"service_cmn",
	"type":4
}`


这是我`.fastRequest`目录中controller名字目录下`DictController`相关的`directory.json`文件。
`{
	"description":"",
	"directory":"/.fastRequest/collections/ROOT~service_cmn~DictController",
	"filePath":"/.fastRequest/collections/ROOT~service_cmn~DictController~",
	"name":"DictController",
	"type":3
}`

**Comment by AWeiIsCoding** [comment]
还有一个问题，请问能否支持一键保存 Navigate 里面所有的api？并按照不同的模块和controller分类。

**Comment by kings1990** [comment]
麻烦检查一下是否有目录**/.fastRequest/collections/ROOT/service_cmn/DictController**，以及目录的权限。

**Comment by AWeiIsCoding** [comment]
是的，存在目录 **/.fastRequest/collections/ROOT/service_cmn/DictController**，以及其权限为**Administrators Allow  FullControl**。

**Comment by kings1990** [comment]
老铁麻烦来我的技术群，需要一下老铁存储的具体参数

**Comment by AWeiIsCoding** [comment]
好的
