### ISSUE TITLE
improper translation

### ISSUE THREAD

**Issue by francisco-vieira** [dromara/fast-request#258]
### Current Version
2023.1.7 -> trial
### Operation steps
- Here's a print of the translation and what it should be
![image](https://github.com/dromara/fast-request/assets/38992847/f5cb12af-4b38-47d4-9cd4-2d03a6559834)
![image](https://github.com/dromara/fast-request/assets/38992847/b7d5dc59-7542-4a3b-a02c-b47b0139a91a)

Language change in message return

### Error Message
error message translated into another language

**Comment by kings1990** [comment]
@francisco-vieira Hi, can you tell me in this tab, does the response text changes language?

<img width="705" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/f1c8926b-d70f-4850-b7d3-39674f8ddf50">

**Comment by kings1990** [comment]
And also want to aks if you have installed some auto-translate plugins?

**Comment by kings1990** [comment]
Did you use i18n in your project? And the response will auto change language by some header key?

**Comment by kings1990** [comment]
@francisco-vieira Hi there, can you please add a header  `"Accept-Language":"en-US".`
It seems before version 2023.1.8, the plugin will add a default header "zh-CN,zh;q=0.8",  I will remove it in plugin version 2023.1.9

**Comment by kings1990** [comment]
Try update plugin version to 2023.1.9+
