### ISSUE TITLE
api保存后，接口改变了参数，api列表的参数列表没有更新，刷新也不行

### ISSUE THREAD

**Issue by floatinghua** [dromara/fast-request#263]
## Suggestion/improvement
第一次保存api了后

![image](https://github.com/dromara/fast-request/assets/38682071/52028b5b-1c25-46f0-9708-5ba622de9242)
![image](https://github.com/dromara/fast-request/assets/38682071/4cb3a1e5-9622-49e6-8b8e-21c5ab1a0227)

接口删除某个参数如图

![image](https://github.com/dromara/fast-request/assets/38682071/d4b573f1-0e14-4199-8ec8-a26678188f1a)

但是再次点击还是有两个参数
![image](https://github.com/dromara/fast-request/assets/38682071/63405bc5-063f-4724-b176-36e4b9192d81)

**Comment by floatinghua** [comment]
版本：2023.1.7.1

**Comment by kings1990** [comment]
保存后再点方法左侧图标FR，每次回显的是保存那一刻的所有内容。

如果修改了方法的url或者参数，又想生成出最新的内容，点击重新生成即可。

<img width="788" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/de119e33-d756-4c3c-9923-05b4590f8b9d">
