### ISSUE TITLE
使用的时候会在项目的根目录创建一个配置文件

### ISSUE THREAD

**Issue by FlowerCard** [dromara/fast-request#272]
### 2023.1.9

在使用的时候会在项目的根目录创建一个配置文件
![image](https://github.com/dromara/fast-request/assets/40333039/dc3b8402-f7d3-4690-93b1-297f6b2cf269)
很多时候要自己去排出这个文件。
这个文件的生成能不能更改一下

**Comment by kings1990** [comment]
这个就如git一样，用git就会有一个.git文件
