### ISSUE TITLE
ai功能优化

### ISSUE THREAD

**Issue by bluedreamteng** [dromara/fast-request#274]
ai美化参数建议加上自定义openai服务地址以及能够用markdown解析库解析出openai输出的json。

**Comment by kings1990** [comment]
openai这一块目前好像没有标准化结构json输出吧

**Comment by bluedreamteng** [comment]
> ai美化参数建议加上自定义openai服务地址以及能够用markdown解析库解析出openai输出的json。

有的 你在promot里加上让它用标准化markdown输出代码，然后用markdown解析工具解析出它输出的代码，这样美化参数的成功率会更高，现在使用过程中，成功率很低，一般都是直接弹出一个提醒，然后我就在提醒中找出json代码 然后手动替换 这样效率太低了

**Comment by kings1990** [comment]
Please upgrade to 2024.1.4
