### ISSUE TITLE
Groovy、Kotlin插件依赖

### ISSUE THREAD

**Issue by liaozan** [dromara/fast-request#275]
看了下 issues，kotlin 插件依赖是为了支持 kotlin，Groovy 插件是用来干嘛呢？
有没有可能其他语言的支持，如kotlin、grovvy变成可选？安装了对应插件才支持对应的语言？（本人强迫症。。不想装多余的插件）

**Comment by kings1990** [comment]
groovy是用来搞前后置脚本的
