### ISSUE TITLE
[建议] 最新版 返回的JSON数据 建议可以支持关键字搜索 

### ISSUE THREAD

**Issue by handsomeliyao** [dromara/fast-request#276]
![image](https://github.com/dromara/fast-request/assets/48710914/ee7489fe-16d3-4a34-9419-602924cdaa9d)

现在json模块变成了不是文本编辑器那种形式，不支持关键字搜索了

可以在Pretty选项中进行搜索，但是都是报警告，不太方便

![image](https://github.com/dromara/fast-request/assets/48710914/b4004152-50f1-4594-ab01-31f6a05e1667)

**Comment by kings1990** [comment]
都是警告应该是你的idea开了什么检查设置，可以点击进去忽略警告。

<img width="538" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/2d7df4de-c6b1-4f82-a009-1eaf56eaa6ef">
