### ISSUE TITLE
保存请求是灰色无法点击

### ISSUE THREAD

**Issue by Ricardo777888** [dromara/fast-request#278]
![image](https://github.com/dromara/fast-request/assets/43259994/5dd0169c-b901-418c-a4ae-05f8e8fcc0c3)

**Comment by kings1990** [comment]
点击购买链接激活插件[https://plugins.jetbrains.com/plugin/16988-restful-fast-request--api-buddy/pricing](https://plugins.jetbrains.com/plugin/16988-restful-fast-request--api-buddy/pricing)
