### ISSUE TITLE
更新频率问题

### ISSUE THREAD

**Issue by DosLee** [dromara/fast-request#285]
基本每两天就能收到版本更新提醒，更新虽然好，但还是请注重现有功能质量的前提下，稳步提升、添加新的功能。
这是我见过的第一个更新版本这么频繁的插件。

**Comment by kings1990** [comment]
最近发现有些代码导致idea启动有些情况下会变卡，确实更新比较频繁给你们带来了不便，见谅。
大版本一般都是202x.y.z，紧急修复一些严重性的bug会出现202x.y.z.1   202x.y.z.2这样之类的版本
