### ISSUE TITLE
可以支持kotlin吗？

### ISSUE THREAD

**Issue by csh159** [dromara/fast-request#287]
## Suggestion/improvement
eg:hope to support parsing of type XX

**Comment by csh159** [comment]
![Uploading 1700552507958.png…]()

**Comment by csh159** [comment]
![1700552507958](https://github.com/dromara/fast-request/assets/4157414/0beeecf3-4c64-4733-bb93-9629dcf15279)

**Comment by kings1990** [comment]
方法名截图看一下，支持kotllin版本的spring系列代码
