### ISSUE TITLE
 Reload apis... 扫描项目的接口过的，maven多项目时卡死idea

### ISSUE THREAD

**Issue by wdkGitHub** [dromara/fast-request#293]
idea  2023.3  最新版本插件
<img width="338" alt="image" src="https://github.com/dromara/fast-request/assets/12813051/4555aa98-3806-4e60-bcab-fadd4b4d3da0">

**Comment by wdkGitHub** [comment]
<img width="641" alt="image" src="https://github.com/dromara/fast-request/assets/12813051/5cfd3f85-11ff-44c2-8bee-fbf4af0952b6">
直接卡死了

**Comment by kings1990** [comment]
使用 SearchEveryWhere替代这个功能，下个版本会加入 classname 搜索

**Comment by kings1990** [comment]
upgrade to 2024.1.1+
