### ISSUE TITLE
[Feature Request]:通过curl导入的url，无法导航到具体的方法上，能不能优化一下？

### ISSUE THREAD

**Issue by testasb** [dromara/fast-request#312]
### Checklist

- [X] I have updated the plugin to the **latest version**
- [X] I have the valid **license** of **Restful Fast Request**
- [X] I searched the [Docs](https://api-buddy.com/en/guide/features/) and I did not find the feature.
- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

现状：当前导入需要提前定位到对应的controller方法上面，但是这种不符合突发bug，测试突然要求马上修复bug，但是这时你正在开发新的功能，所以定位到方法上的设定感觉有些鸡肋，找寻接口的时间也是不容忽视的

期望：根据现有的url定位功能做一下优化（附图），因为现在可以查看到url，所以才会想能不能点击定位的时候用url去 apis那个列表去匹配一下，然后跳转
<img width="931" alt="image" src="https://github.com/dromara/fast-request/assets/149943852/ebe80d3d-1000-4591-a8ec-ac9331de9d9b">

**Comment by kings1990** [comment]
Please upgrade to 2024.1.4
