### ISSUE TITLE
[Bug]: 官方网站搜索功能失效

### ISSUE THREAD

**Issue by DosLee** [dromara/fast-request#315]
### 检查项

- [X] 我已经将插件更新为**最新版**
- [X] 我拥有 **Restful Fast Request** 的有效**许可证**
- [X] 我查阅了 [文档](https://api-buddy.cn) 以及 [功能](https://api-buddy.cn/guide/features/) 相关介绍，并仔细检查了我的配置。
- [X] 我查阅 [FAQ](https://api-buddy.com/guide/faq.html) 并且不知道如何解决
- [X] 我搜索了已关闭的Issue，但没有找到答案

### 您使用的是以下哪个操作系统

- [X] macOS
- [ ] Windows
- [ ] Linux

### IDEA 版本号

2024.1

### 插件版本号

2024.1.4

### Bug 详情

 [官方网站](https://api-buddy.cn/) 搜索失效，搜索栏可以搜索出想要的条目，点击后显示页面404.
 
 顺便把想搜索的问题，写到这里吧。超时时间不能设置为无限吗？比如超时时间设置为-1或0。

### Error log

![20240424-163910@2x](https://github.com/dromara/fast-request/assets/20384730/03ac9359-3883-4080-8de7-c6734946ba60)

**Comment by kings1990** [comment]
fixed
