### ISSUE TITLE
[Bug]:无法跳转到对应的接口

### ISSUE THREAD

**Issue by Chaos-ting** [dromara/fast-request#316]
### 检查项

- [X] 我已经将插件更新为**最新版**
- [X] 我拥有 **Restful Fast Request** 的有效**许可证**
- [X] 我查阅了 [文档](https://api-buddy.cn) 以及 [功能](https://api-buddy.cn/guide/features/) 相关介绍，并仔细检查了我的配置。
- [X] 我查阅 [FAQ](https://api-buddy.com/guide/faq.html) 并且不知道如何解决
- [X] 我搜索了已关闭的Issue，但没有找到答案

### 您使用的是以下哪个操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux

### IDEA 版本号

2024.1

### 插件版本号

2024.1.4

### Bug 详情

![图片](https://github.com/dromara/fast-request/assets/57206775/68800b1f-93ca-4386-bd42-033553002378)
![图片](https://github.com/dromara/fast-request/assets/57206775/2d0575d2-492c-4c29-96c1-9e7594e1ab3c)
点击按钮后并不能跳转到正确的地址

**Comment by kings1990** [comment]
点击重新生成，注意方法名不要重载
