### ISSUE TITLE
[Feature Request]: Switch off trailing slash while saving for api

### ISSUE THREAD

**Issue by ostfale** [dromara/fast-request#326]
### Checklist

- [X] I have updated the plugin to the **latest version**
- [X] I have the valid **license** of **Restful Fast Request**
- [X] I searched the [Docs](https://api-buddy.com/en/guide/features/) and I did not find the feature.
- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Describe the feature

![image](https://github.com/dromara/fast-request/assets/2959318/2ff590d6-46e1-4173-a3e9-a3db1ee5e825)

Spring boot application with a controller. Using the gutter icon creates a request `/internal/ws` .  Saving this to api results in adding a trailig slash (see screensho). Spring does not interpret this trailig slash as before so it doesnt work sending the request. Is there a way to avoid the trailing slash while saving it to api tree?

**Comment by kings1990** [comment]
Does all APIs have a suffix /?

**Comment by kings1990** [comment]
Please check the following config and make it empty. This filed is empty by default, I guess you have fill in '/'

<img width="1180" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/e67b2724-3ac0-46f9-a88b-4ee1fcde657f">

**Comment by ostfale** [comment]
![image](https://github.com/dromara/fast-request/assets/2959318/cb2adcee-40ca-47dd-8103-9a1aa8884159)

No, its empty (default)

**Comment by kings1990** [comment]
Could you please Join my [slack](https://join.slack.com/t/restfulfastrequest/shared_invite/zt-1we57vum8-TALhTHI2uNmPF2bx1NDyWw) and so we can communicate better

**Comment by ostfale** [comment]
I'll do it later on :-)

**Comment by kings1990** [comment]
Also check this config.
<img width="1585" alt="image" src="https://github.com/dromara/fast-request/assets/8969637/f0a4f784-13fb-453a-9ffd-79eb2f786a78">

**Comment by kings1990** [comment]
Could you show me the controller code?

**Comment by ostfale** [comment]
With this EAP Version the plugin works as expected. Thx for fast help! :-)
