### ISSUE TITLE
[Bug]:调试接口的请求路径

### ISSUE THREAD

**Issue by 66qingcun** [dromara/fast-request#328]
### 检查项

- [X] 我已经将插件更新为**最新版**
- [X] 我拥有 **Restful Fast Request** 的有效**许可证**
- [X] 我查阅了 [文档](https://api-buddy.cn) 以及 [功能](https://api-buddy.cn/guide/features/) 相关介绍，并仔细检查了我的配置。
- [X] 我查阅 [FAQ](https://api-buddy.com/guide/faq.html) 并且不知道如何解决
- [X] 我搜索了已关闭的Issue，但没有找到答案

### 您使用的是以下哪个操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux

### IDEA 版本号

2024.1.2

### 插件版本号

2024.1.5.1

### Bug 详情

当接口控制器继承了其他 interface时，调试接口时无法读取到接口的完整请求路径

### Error log

![image](https://github.com/dromara/fast-request/assets/113237938/d12fe05f-66d8-4966-8d13-c68feaddccb1)
![image](https://github.com/dromara/fast-request/assets/113237938/383d9b5d-f0f3-4d39-a2d9-6c38c6adbb6d)

**Comment by 66qingcun** [comment]
作者已解决，效率非常高，点赞

**Comment by kings1990** [comment]
> 作者已解决，效率非常高，点赞

还没发布，将在 2024.1.6 发布
