### ISSUE TITLE
[Bug]:某个项目用这个插件点开是空白的

### ISSUE THREAD

**Issue by wangjiancheng180** [dromara/fast-request#329]
### Checklist

- [X] I have updated the plugin to the **latest version**
- [X] I have the valid **license** of **Restful Fast Request**
- [X] I followed the [docs](https://api-buddy.com) and the [features](https://api-buddy.com/en/guide/features/) introduction and I double checked my configuration.
- [X] I have searched [FAQ](https://api-buddy.com/guide/faq.html) and I did not find the answer.
- [X] I have searched closed issue and I did not find the answer.

### Which operating system are you using?

- [ ] macOS
- [X] Windows
- [ ] Linux

### IDEA version

2024-01-03

### Plugin version

2024.1.5.1

### Describe the bug

有一个项目打开插件啥都没有

### Error log

<img width="411" alt="2558CBE5-1010-4a9d-BA59-A93CB072FFC0" src="https://github.com/dromara/fast-request/assets/63392742/852a824b-dfe0-49e4-91bb-08781d4d6e5a">

**Comment by kings1990** [comment]
重启试试

**Comment by kings1990** [comment]
idea.log 有报错信息吗，有的话提供一下

**Comment by wangjiancheng180** [comment]
> 重启试试

有用哎，真的是重启解决99%的问题，插件本身没有报错，不知道为什么会有这种问题，这个时常会发生

**Comment by kings1990** [comment]
看 idea.log，里面找找关于fast request 的日志

**Comment by kings1990** [comment]
长时间未回复
