### ISSUE TITLE
[Bug]: 使用自定义Controller组合注解时, 插件无法识别出正确的url

### ISSUE THREAD

**Issue by cacuts-c** [dromara/fast-request#332]
### 检查项

- [X] 我已经将插件更新为**最新版**
- [X] 我拥有 **Restful Fast Request** 的有效**许可证**
- [X] 我查阅了 [文档](https://api-buddy.cn) 以及 [功能](https://api-buddy.cn/guide/features/) 相关介绍，并仔细检查了我的配置。
- [X] 我查阅 [FAQ](https://api-buddy.com/guide/faq.html) 并且不知道如何解决
- [X] 我搜索了已关闭的Issue，但没有找到答案

### 您使用的是以下哪个操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux

### IDEA 版本号

2024.1.2

### 插件版本号

2024.1.6

### Bug 详情

![image](https://github.com/dromara/fast-request/assets/161403052/d246fba9-0418-492a-9cfb-148f7b3629c6)
如上图, 我自定义了一个@TRestController注解, 但是在使用时, 插件并未检测到其注解上面的url路径

**Comment by kings1990** [comment]
不支持自定义注解

**Comment by cacuts-c** [comment]
自定义组合注解目前idea官方都已经支持了, 请问你们后期也不会考虑吗

**Comment by kings1990** [comment]
等我后续研究一下

**Comment by cacuts-c** [comment]
好的, 谢谢, 希望有时间可以完善一下

**Comment by kings1990** [comment]
2024.1.7加入支持

**Comment by cacuts-c** [comment]
试过可以啦, 非常感谢!!

**Comment by kings1990** [comment]
Fixed in 2014.1.6.2
