### ISSUE TITLE
[Bug]: Environment variable values set in pre-request script are not used in current request

### ISSUE THREAD

**Issue by Todd-PDCFlow** [dromara/fast-request#333]
### Checklist

- [X] I have updated the plugin to the **latest version**
- [X] I have the valid **license** of **Restful Fast Request**
- [X] I followed the [docs](https://api-buddy.com) and the [features](https://api-buddy.com/en/guide/features/) introduction and I double checked my configuration.
- [X] I have searched [FAQ](https://api-buddy.com/guide/faq.html) and I did not find the answer.
- [X] I have searched closed issue and I did not find the answer.

### Which operating system are you using?

- [X] macOS
- [ ] Windows
- [ ] Linux

### IDEA version

IntelliJ IDEA 2024.1.4 (Ultimate Edition)

### Plugin version

2024.1.6

### Describe the bug

If I set an environment variable in the pre-request script, the new value is NOT used by the current request

Request is configured with the environment variable {{batchId}} as a Path Param
![RequestConfig](https://github.com/user-attachments/assets/3cad6e0d-5a72-4e13-978f-cdfad4a8f39c)

The environment variable batchId is changed during the Api-Level pre-request Script and validated via console.print statements
![pre-request script](https://github.com/user-attachments/assets/f49bd1a2-6964-4c0e-8553-a792c12d16f0)

The environment variable is also confirmed via the post-request Script
![post-request script](https://github.com/user-attachments/assets/ea4cb38d-841f-46cc-8b94-a7e923e54606)

You can see by the console output the previous value of the environment variable batchId is being used in the current request, not the new value that was set during the pre-request script
![console output](https://github.com/user-attachments/assets/63f98147-4d0f-4d94-8569-87caeb8d11d3)

**Comment by kings1990** [comment]
@Todd-PDCFlow 
Thank you very much for describing the process of generating the bug in great detail. I will fix it in the next version. So in current you need to send the request again to insure the request use the new environment value

**Comment by kings1990** [comment]
Fixed in 2014.1.6.2
