### ISSUE TITLE
[Bug]:SearchAPI搜索不到

### ISSUE THREAD

**Issue by oneCatZz** [dromara/fast-request#337]
### 检查项

- [X] 我已经将插件更新为**最新版**
- [X] 我拥有 **Restful Fast Request** 的有效**许可证**
- [X] 我查阅了 [文档](https://api-buddy.cn) 以及 [功能](https://api-buddy.cn/guide/features/) 相关介绍，并仔细检查了我的配置。
- [X] 我查阅 [FAQ](https://api-buddy.com/guide/faq.html) 并且不知道如何解决
- [X] 我搜索了已关闭的Issue，但没有找到答案

### 您使用的是以下哪个操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux

### IDEA 版本号

2024.2

### 插件版本号

2024.1.6.3

### Bug 详情

当我的接口没有编写路径时SearchAPI无法搜索到，我们项目接口众多又是Restful规范，搜索不到的话就很难找接口了，用其他的插件能搜索到，但是我不想装多余的插件
![image](https://github.com/user-attachments/assets/190efe97-e431-4290-8a09-88e394c3d56f)
![image](https://github.com/user-attachments/assets/ca6cadc9-ca8f-4e6c-b220-b8342f8e2527)
![image](https://github.com/user-attachments/assets/78c6dfb5-0785-4611-807a-ec5904139a18)

**Comment by kings1990** [comment]
<img width="1222" alt="image" src="https://github.com/user-attachments/assets/1d72f516-6506-4bc1-a1ff-9fe8903bcbc8">

建议添加搜索策略，应该是排在了后面你没找到

**Comment by kings1990** [comment]
<img width="1318" alt="image" src="https://github.com/user-attachments/assets/658f4a32-9591-45a1-9ec5-e73f874d1dd2">
或者在搜索的时候左侧加类型，例如 **post /customer**

**Comment by oneCatZz** [comment]
![image](https://github.com/user-attachments/assets/d03cf767-136f-4e4b-85e7-5546c23298f7)
![image](https://github.com/user-attachments/assets/3cf6fcde-e542-43c4-9574-819cfdf58969)
排序似乎有点问题，post接口非常多，我一直点更多可能才翻得到，put请求就比较少稍微看一下就能找到，要是更符合的排前面就好了

**Comment by kings1990** [comment]
下个版本排序优化一下应该就 ok 了

**Comment by kings1990** [comment]
Please upgrade to 2024.1.7
