### ISSUE TITLE
[Bug]:更新到2024.1.7版本后，【项目全局参数】点击没反应

### ISSUE THREAD

**Issue by xiewanghui** [dromara/fast-request#342]
### 检查项

- [X] 我已经将插件更新为**最新版**
- [X] 我拥有 **Restful Fast Request** 的有效**许可证**
- [X] 我查阅了 [文档](https://api-buddy.cn) 以及 [功能](https://api-buddy.cn/guide/features/) 相关介绍，并仔细检查了我的配置。
- [X] 我查阅 [FAQ](https://api-buddy.com/guide/faq.html) 并且不知道如何解决
- [X] 我搜索了已关闭的Issue，但没有找到答案

### 您使用的是以下哪个操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux

### IDEA 版本号

2024.2.2

### 插件版本号

2024.1.7

### Bug 详情

更新到2024.1.7版本后，【项目全局参数】点击没有任何反应，导致设置不了全局参数，影响使用
![image](https://github.com/user-attachments/assets/311797a7-0686-4c41-ac84-a2a68b2c8003)

### Error log

![image](https://github.com/user-attachments/assets/46e60aa7-6313-4b70-9015-95a45fd6136e)

**Comment by kings1990** [comment]
麻烦贴一下报错日志，或者进入微信群扫描联系一下我
![image](https://github.com/user-attachments/assets/202ee9c0-792b-4d76-82b6-9d57270459c4)

**Comment by kings1990** [comment]
upgrade to 2024.1.7.1
