### ISSUE TITLE
[Feature Request]:希望增加根据注解忽略解析参数

### ISSUE THREAD

**Issue by kingxjs** [dromara/fast-request#344]
### 检查项

- [X] 我已经将插件更新为**最新版**
- [X] 我拥有有效的 **Restful Fast Request** **许可证**
- [X] 我查阅了 [功能文档](https://api-buddy.com/en/guide/features/) 并且没有发现该功能
- [X] 我搜索了现有问题，没有其他人提出类似的功能
- [X] 我认为 25% 以上的用户对此功能持积极态度

### 描述功能

现在支持字段名以及字段类型忽略解析，希望增加根据注解忽略解析参数
```
可以根据 @CurrentUserPrincipal 进行忽略解析
@RequestMapping(value = "/test/{id}", method = RequestMethod.POST)
public void test(@CurrentUserPrincipal CurrentUser currentUser, @PathVariable String id) {
   
}
```

**Comment by kings1990** [comment]
试试这个

[https://api-buddy.cn/guide/faq.html#s-%E8%A7%A3%E6%9E%90%E5%A6%82%E4%BD%95%E5%BF%BD%E7%95%A5%E6%9F%90%E4%B8%AA%E5%AD%97%E6%AE%B5](https://api-buddy.cn/guide/faq.html#s-%E8%A7%A3%E6%9E%90%E5%A6%82%E4%BD%95%E5%BF%BD%E7%95%A5%E6%9F%90%E4%B8%AA%E5%AD%97%E6%AE%B5)


![image](https://github.com/user-attachments/assets/6207d6be-7d2e-44fb-a751-6b1b6bcb0891)

**Comment by kings1990** [comment]
加了注解就容易侵入代码，或者提供一个比较常用的注解
