### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by 718981206** [dromara/fast-request#353]
### 检查项

- [X] 我已经将插件更新为**最新版**
- [X] 我拥有 **Restful Fast Request** 的有效**许可证**
- [X] 我查阅了 [文档](https://api-buddy.cn) 以及 [功能](https://api-buddy.cn/guide/features/) 相关介绍，并仔细检查了我的配置。
- [X] 我查阅 [FAQ](https://api-buddy.com/guide/faq.html) 并且不知道如何解决
- [X] 我搜索了已关闭的Issue，但没有找到答案

### 您使用的是以下哪个操作系统

- [ ] macOS
- [X] Windows
- [ ] Linux

### IDEA 版本号

2024.3.11

### 插件版本号

2024.1.9.1

### Bug 详情

在API调试过程中，出现请求重试的情况，配置中似乎没有对重试次数的控制？

当前调整超时时间为比较大的值才能避免二次请求。 但有时需要调试低超时时间的情况，后续有无增加控制重试配置的计划？

### Error log

无

**Comment by kings1990** [comment]
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/6c986ebc-69b4-4c8b-9061-817beae06234" />
