### ISSUE TITLE
关于 request url 是常量的问题

### ISSUE THREAD

**Issue by superleeyom** [dromara/fast-request#38]
如果我的 controller 里面的 url 如下写法抽离到常量中：

```java
@GetMapping(Url.Factor.ACCT_BP_FACTOR)
public ApiResponse<BpFactorUpdateVO> getAcctBp(String finAccountId){

}
```
点击🚀，无法读取里实际的 url，直接原封不动的取到常量原值
![image](https://user-images.githubusercontent.com/22115219/149490783-a443aa36-06ed-4b2d-975d-b33faec3c336.png)

虽然有 url replace config，但是对于这种似乎不太适用，不可能把所有的录入，idea plugin sdk 是无法读取到对应常量的实际值吗？ 
```java
public interface Url {
    interface Factor {
        String ACCT_BP_FACTOR =  "xxx";
    }
}

```

**Comment by kings1990** [comment]
下个版本v2.1.2完善

**Comment by ddxl123** [comment]
> Will be improved in V2.1.2

什么时候发布呀
