### ISSUE TITLE
停用了idea自带的插件markdown插件，会停用fastRequest插件

### ISSUE THREAD

**Issue by junziqiao** [dromara/fast-request#46]
## 建议/改进(Suggestion/improvement)
eg:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/41858086/155301673-3a0aa113-0cb8-4ad2-b100-d7f161a677e1.png">

**Comment by kings1990** [comment]
The plug-in uses the Markdown plug-in, which generates the information needed for the issue when an error occurs
