### ISSUE TITLE
api请求路径包含常量 路径生成错误

### ISSUE THREAD

**Issue by zepinZheng** [dromara/fast-request#47]
### 当前使用版本(Current Version)
2.1.2
### 重现步骤(Repeat steps)
![image](https://user-images.githubusercontent.com/45777960/155489038-efc5e5ad-1f8e-4683-9d63-12b081c53ede.png)
api请求路径包含常量 解析生成路径错误 常量部分解析错误

**Comment by kings1990** [comment]
Please show me your source code of method
