### ISSUE TITLE
Can I change the parameters check default?

### ISSUE THREAD

**Issue by Frankle97** [dromara/fast-request#49]
Currently, press the quick request, all parameters are checked by default.

But, I want to make sure that all parameters are not checked by default.

Can I know how to do it?

**Comment by kings1990** [comment]
You can click checkbox in table header.It is available in **Headers | Path param | Url Params| URL Encoded | Multipart**
But if you want not check the params, This defeats the purpose of plugin.
I don not know why you want not check the parameters.

![image](https://user-images.githubusercontent.com/8969637/156501213-d836aa33-2826-4e2f-afdc-fd58c0f1e682.png)

**Comment by Frankle97** [comment]
My API mostly have too many parameters.

Currently, all parameters are checked by default,  i have to press the option that is not checked on top every time.

For now, does not problem for using. 
However i think if has turn on default option, useful more comfortable.

Thank you to developed useful utility : )

**Comment by kings1990** [comment]
Thanks for your feedback.
Next version, i will add a checkbox to make whether to generate **URL and Body params**, just generate path param

**Comment by Frankle97** [comment]
Thanks for providing useful tools!
