### ISSUE TITLE
对于PostMapping不能搜索出来,但是PutMapping可以(同一个路径下,不写具体的请求名)

### ISSUE THREAD

**Issue by QinHongZhe** [dromara/fast-request#53]
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)
对于PostMapping不能搜索出来,但是PutMapping可以(同一个路径下,不写具体的请求名)

![image](https://user-images.githubusercontent.com/25653313/157576359-394d6471-582d-4999-8eea-9e8022bbe796.png)

![image](https://user-images.githubusercontent.com/25653313/157576396-dad4ced6-4fad-419b-80b3-a5aba4f76584.png)

**Comment by kings1990** [comment]
不大可能吧,是不是输入有误

![image](https://user-images.githubusercontent.com/8969637/157581528-918b60c7-f3ee-4a1c-b052-0e771fe01d96.png)

**Comment by QinHongZhe** [comment]
![image](https://user-images.githubusercontent.com/25653313/157605094-f114667a-662a-4a09-8fac-6480fbaf0ab0.png)

我们可能搜的方式不太一样.你搜的是Controller 的名称,我搜的  是方法名.  形式如上图,   post和put的参数一致.都没有具体的"/XXXX" 这种接口形式. 通过  PutMapping PostMapping 这样就搜不到.

**Comment by kings1990** [comment]
那你postMapping里面填了什么，截图被折叠了

**Comment by QinHongZhe** [comment]
postMapping 里面什么都没填,    截图折叠问题是一个插件折叠的.   
![image](https://user-images.githubusercontent.com/25653313/157620908-f4e4c168-0827-48e2-86a2-7460ca57929a.png)
![image](https://user-images.githubusercontent.com/25653313/157620942-64e497c6-0d4e-4045-9fe3-388fda03e773.png)


我也不知道是索引还是哪里的问题,刚刚装上,然后试了下.发现问题.就来提issue了

**Comment by kings1990** [comment]
搜索关键字会基于PostMapping里面的value或者path属性,没有填写不能查找，你要么根据controller上面的搜索，按照方法搜索，idea自带的搜索就可以搜到了
