### ISSUE TITLE
可否增加项目部署或者启动的文档

### ISSUE THREAD

**Issue by QinHongZhe** [dromara/fast-request#54]
## 建议/改进(Suggestion/improvement)
可否增加项目部署或者启动的文档,方便想提pull request 的人可以快速运行项目

**Comment by kings1990** [comment]
这是官方文档，[https://plugins.jetbrains.com/docs/intellij/welcome.html](https://plugins.jetbrains.com/docs/intellij/welcome.html) 先阅读官方文档，运行gradle idea插件下的runIde启动项目
