### ISSUE TITLE
目前支持认证吗？支持的话怎么操作呢？

### ISSUE THREAD

**Issue by lwxk** [dromara/fast-request#56]
## 建议/改进(Suggestion/improvement)
eg:希望支持xx类型的解析(eg:hope to support parsing of type XX)

**Comment by lwxk** [comment]
> 

不是token，就是Basic，用户名、密码认证

**Comment by kings1990** [comment]
暂时没有,后续版本我想想，不过也是基于headers，最终转化成Authorization的

**Comment by kings1990** [comment]
Add **Basic Auth** to Headers Value

**Comment by diedie123** [comment]
可以有登录接口，然后自动带上cookie吗？

**Comment by kings1990** [comment]
> 可以有登录接口，然后自动带上cookie吗？

2022.1.6支持快速将cookie塞入到头了
