### ISSUE TITLE
对kotlin代码不支持

### ISSUE THREAD

**Issue by DreamYa0** [dromara/fast-request#58]
对kotlin的代码好像不支持，左边也没小火箭的图标，用快捷键生成但是打开右边的窗口也会报错

**Comment by kings1990** [comment]
请求支援

**Comment by DreamYa0** [comment]
不介意插件付费，但是希望添加对kotlin代码的支持，感谢

**Comment by kings1990** [comment]
是的,目前kotlin不支持，主要我对kotlin不大熟悉，目前迭代又太频繁,缺少帮手。。

**Comment by kings1990** [comment]
2022.1.7 Kotlin已支持 @DreamYa0 
kotlin + spring系列
