### ISSUE TITLE
Last Free version 2.1.3.0(Fix block bug)

### ISSUE THREAD

**Issue by kings1990** [dromara/fast-request#61]
### Note Users using V2022.1.4.0 + just ignore this 
This version fix **block bug** ` Fix Light files should have PSI only in one project`

Install step: `Download this version -> Setting -> Install Plugin from Disk... -> Choose this version -> restart`

### 使用v2022.1.4.0+的用户请忽略

该版本修复了**阻断性bug** `Fix Light files should have PSI only in one project`

安装步骤:`下载该版本 -> Setting -> Install Plugin from Disk...>选择该版本->重启`

[fast-request-2.1.3.0.zip](https://github.com/dromara/fast-request/files/8312828/fast-request-2.1.3.0.zip)

**Comment by lzl-66** [comment]
高版本安不了滴

**Comment by kings1990** [comment]
可以使用2022系列

**Comment by ngoyatnomman** [comment]
idea2022.2.4安装不了

**Comment by kings1990** [comment]
@ngoyatnomman   可以使用2022.2.x系列 ，入微信群打6折的，现在便宜

**Comment by kings1990** [comment]
@OfferingCotton 
Free version
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/8969637/220825655-601019c1-3322-49aa-ae79-3cd0c0418534.png">

Paid version

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/8969637/220825701-3d54a4cb-b903-42cd-99ce-9f9393fcf7a9.png">
