### ISSUE TITLE
About response error 

### ISSUE THREAD

**Issue by pattarakorn-wind** [dromara/fast-request#62]
(Current Version)
2022.1.4.0

Some error response is not JSON 
![Screen Shot 2565-03-22 at 16 10 33](https://user-images.githubusercontent.com/88589745/159446087-ea1a6025-7595-4f4b-a63f-d3ac9d9ce6f3.png)

But use curl from Fast request or use postman 
![Screen Shot 2565-03-22 at 16 11 36](https://user-images.githubusercontent.com/88589745/159446281-b4957b3a-f0b7-4273-b47e-29798ce13127.png)
![Screen Shot 2565-03-22 at 16 12 37](https://user-images.githubusercontent.com/88589745/159446474-394840c5-6f86-4ae6-98fd-69d29016e829.png)

Detail in code 
throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Password not match");

But response error from validated by annotation(@NotBlank) return JSON message in Fast request
![Screen Shot 2565-03-22 at 16 17 43](https://user-images.githubusercontent.com/88589745/159447381-0a3d9df4-c89f-488d-8ab7-c13f4f643704.png)

Thanks and best regard

**Comment by kings1990** [comment]
Maybe you can add *Accept* in header value 

![image](https://user-images.githubusercontent.com/8969637/159466100-dd38348a-9a50-4a53-942c-0ee743f0fb24.png)

**Comment by kings1990** [comment]
default sort is **text/html,application/json,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8**
next version i will make Accept to */* by default, and you will get json by default

**Comment by pattarakorn-wind** [comment]
For now, I got JSON already thank you for your support

**Comment by kings1990** [comment]
Also thanks for your feedback. 🙌
