### ISSUE TITLE
希望考虑支持联动web项目并自动获取端口等信息

### ISSUE THREAD

**Issue by ForteScarlet** [dromara/fast-request#64]
## 建议/改进(Suggestion/improvement)
在idea中，有一个 `services` 的 tab，以 `Spring Boot` 项目为例， 它可以添加并统一管理所有的 `Spring Boot` 项目模块的配置和进程，比如如下图的效果：
<img width="395" alt="image" src="https://user-images.githubusercontent.com/40045247/159635655-fd912202-9df6-433c-8ed7-da8b011a950b.png">

在这里，它似乎能够自动检测出运行中的模块配置和其对应进程的端口号。（我不知道对于其他的web相关框架来讲是不是也有类似的能力）

不知道能否让插件也支持检测当前环境中启动的进程，以及他们对应的项目和端口号呢？
这样的话，除了提前配置死环境信息以外，还可以直接选择一个当前正在执行的模块和进程进行使用，可以免除一定的配置操作，也可以不用在端口号发生变更的时候再修改配置。

**Comment by kings1990** [comment]
这种可能只能支持springboot系列

**Comment by ForteScarlet** [comment]
我倒是还看到能添加一些 `node.js` 相关的配置类型，但是不知道是不是跟web相关的，也不知道它的支持效果是什么样的 ..

**Comment by kings1990** [comment]
Please upgrade to 2023.1.1+

Document: [https://dromara.gitee.io/fast-request/guide/features/projectLevelDomainConfig.html](https://dromara.gitee.io/fast-request/guide/features/projectLevelDomainConfig.html)

**Comment by kings1990** [comment]
[https://dromara.org/fast-request/guide/features/autoDomain.html](https://dromara.org/fast-request/guide/features/autoDomain.html)
 2023.1.4版本开始支持
