### ISSUE TITLE
生成uri时路径参数不能正常赋值

### ISSUE THREAD

**Issue by WROIATE** [dromara/fast-request#66]
### 当前使用版本(Current Version)
2.1.3
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)

<img width="557" alt="image" src="https://user-images.githubusercontent.com/44677306/161967338-0184ec97-b315-473a-97c5-cafe93ec1163.png">

<img width="591" alt="image" src="https://user-images.githubusercontent.com/44677306/161967215-7e2eb0bf-6332-4340-9214-c7a52efb07e9.png">

### 报错信息(Error Message)
Correct url required

**Comment by kings1990** [comment]
正则表达式目前不支持，范围太广，比方说/{id}这种情况是可以的 但是/{id:.*}不支持

**Comment by WROIATE** [comment]
了解
