### ISSUE TITLE
窗口无法初始化

### ISSUE THREAD

**Issue by yejiaqi1** [dromara/fast-request#67]
### 当前使用版本(Current Version)
2022.1.6
### 重现步骤(Repeat steps)
打开idea然后就报插件错误错误内容无法初始化窗口
- 最好提供gif动图(It's best to provide a GIF)
![image](https://user-images.githubusercontent.com/89404550/163563299-a9300872-8313-4a31-a377-dc4dc64e626e.png)

**Comment by kings1990** [comment]
你的证书有问题吧，可以点击只用或者正版license

**Comment by jiadsii** [comment]
不是这样的 2022 idea内部自动绑定了一个 openApi 这是对他们冲突  而且这是一个bug 实现不行就用别的插件代替就好了

**Comment by kings1990** [comment]
什么意思？没看明白，内部自动绑定了一个 openApi 对他们冲突 没理解，请指教
