### ISSUE TITLE
basic auth的密码能不能不强制必须填写

### ISSUE THREAD

**Issue by MrLiu94** [dromara/fast-request#68]
## 建议/改进(Suggestion/improvement)
basic auth的密码能不能不强制必须填写

**Comment by kings1990** [comment]
密码是空？还能这么玩

**Comment by kings1990** [comment]
2022.1.9给与支持,抱歉,之前一直以为密码为空是不可以的

**Comment by MrLiu94** [comment]
> 2022.1.9给与支持,抱歉,之前一直以为密码为空是不可以的

非常感谢！
