### ISSUE TITLE
支持快捷键跳转至搜索

### ISSUE THREAD

**Issue by dragon-zzm** [dromara/fast-request#70]
## 建议/改进(Suggestion/improvement)
![lQLPDhtZMYauDE9SzQN9sOJQwBtjBucfAmLOyd9ANwA_893_82](https://user-images.githubusercontent.com/80671201/164135286-d7562d56-ac09-4397-b4c3-6e44f4c0f160.png)
希望能通过快捷键跳转该搜索tab

**Comment by kings1990** [comment]
update to 2022.1.9
