### ISSUE TITLE
search api时查询到多个匹配的url,建议高亮匹配上的字符或者按照匹配度排序

### ISSUE THREAD

**Issue by hl19950706** [dromara/fast-request#76]
当seach到多个url时,建议按照匹配度排个序或者高亮一下匹配上的字符
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/50948392/165241981-c951eddb-31a4-4aeb-b02c-056c8e1a962d.png">

**Comment by kings1990** [comment]
![image](https://user-images.githubusercontent.com/8969637/165249208-2b8f25cc-280c-429b-8fb0-25e59883bcd9.png)
后面的版本有这个功能的
