### ISSUE TITLE
建议增加url配置占位字符串功能

### ISSUE THREAD

**Issue by linjunli01** [dromara/fast-request#85]
## 建议/改进(Suggestion/improvement)
在项目中，控制器的url有可能不是完整的，而是由配置中心统一拼接的，因此，希望能够加入类似于占位符的配置，在自动生成url时填充指定字符串。如图片所示，红框中的.do为自动拼接
![1](https://user-images.githubusercontent.com/35566929/170457902-7a2fee92-7bf5-4808-b13d-a8809728e3a3.png)

**Comment by kings1990** [comment]
update to 2022.2.1
