### ISSUE TITLE
建议API分组合并/自由组合/保存指定组

### ISSUE THREAD

**Issue by linjunli01** [dromara/fast-request#86]
## 建议/改进(Suggestion/improvement)
你好，我在保存API时遇到了一个尴尬的问题：API默认是保存在类文件名的组别下面，但是当我重命名以后，新的API保存依然是类文件名组别（而不是我重命名的组别）。然后问题是我没办法很好的把这些API归类在一起。如下图所示，我没办法将两个同名的组合并在一起（都是重命名过的）。因此，我建议：
1.保存API时可以指定已存在的组
2.或者，APIs界面，可以组合，或者拖到API到另外的组
![2](https://user-images.githubusercontent.com/35566929/170643479-d20a1689-7026-47c9-88f7-a0014679889e.png)

**Comment by kings1990** [comment]
正在考虑中....后面出一个功能一个API，多个分组参数

**Comment by kings1990** [comment]
update to 2022.2.1
