### ISSUE TITLE
2022.1.10 版不能导出Word 文档

### ISSUE THREAD

**Issue by 029ye** [dromara/fast-request#87]
### 当前使用版本(Current Version)
2022.1.10
### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)

导出Word 文档，变成HTML，

### 报错信息(Error Message)
无

**Comment by kings1990** [comment]
感谢反馈,确实是不经意制造了一个bug

**Comment by kings1990** [comment]
update to 2022.2.1
