### ISSUE TITLE
导出文档，添加相应结果说明，以及提供中文的的文档

### ISSUE THREAD

**Issue by 029ye** [dromara/fast-request#88]
## 建议/改进(Suggestion/improvement)
导出文档，添加相应结果说明，以及提供中文的的文档

**Comment by kings1990** [comment]
结果你执行一下请求再导出就行了，翻译的话都是常规的单词，没理解你说的中文文档啥意思

**Comment by kings1990** [comment]
文档中的单词都是常见的标准术语，不涉及到中英
