### ISSUE TITLE
上传文件时无法上传多个

### ISSUE THREAD

**Issue by caseor** [dromara/fast-request#91]
### 当前使用版本(Current Version)
2022.1.10.1

### 重现步骤(Repeat steps)
- 最好提供gif动图(It's best to provide a GIF)

![FastRequest](https://caseor.gitee.io/resources/img/202206100340.gif)

![Postman](https://caseor.gitee.io/resources/img/202206100346.gif)

### 报错信息(Error Message)

上传多个文件也是基本的需求，希望能够更加的完善，谢谢啦~

**Comment by caseor** [comment]
https://caseor.gitee.io/resources/img/202206100340.gif  
https://caseor.gitee.io/resources/img/202206100346.gif

**Comment by kings1990** [comment]
没看明白是解析不支持还是发生请求错误

**Comment by kings1990** [comment]
update to 2022.2.1
