### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by chenmingyin** [dromara/fast-request#92]
## 建议/改进(Suggestion/improvement)
1.返回结果增加字段注释，现在只有请求参数有字段注释；
2.多设备同步功能，现在如果在不同设备上使用的话，只能重新配置环境和接口了，全部得重来一遍，国内是否可以用内置gitee之类的来做同步；
3.现在只有导出到PostMan，是否可以增加导出到ApiPost、ApiFox的功能。

**Comment by kings1990** [comment]
3不大可能去实现

**Comment by kings1990** [comment]
2目前可以通过导入导出来实现，1后面我考虑一下
