### ISSUE TITLE
Enquiry - External (public) REST Request

### ISSUE THREAD

**Issue by Les-Linux** [dromara/fast-request#93]
Hello,

I am testing out your plugin and have a question relating to external rest api calls. When I try to test an external api call such as [REST-API]([https://api.ipify.org?format=json](https://api.ipify.org/?format=json)) I receive the message 'Correct url required' which is shown under the 'Raw' tab (image attached).

How do I resolve this error in order to test external (public) REST API endpoints?

With sincere regards.

Le
![Screenshot 2022-06-14 at 10 38 36](https://user-images.githubusercontent.com/1759713/173547541-786d8f20-d95e-4164-9e33-d1f664c4b1f6.png)
s

**Comment by Les-Linux** [comment]
nvm - figured it out :)

**Comment by kings1990** [comment]
@Les-Linux Next version, i will bring temp api(api not releate the code) to plugin
