### ISSUE TITLE
希望支持Spring Gateway网关

### ISSUE THREAD

**Issue by fujiakai** [dromara/fast-request#94]
## 建议/改进(Suggestion/improvement)
eg:希望支持xx类型的解析(eg:hope to support parsing of type XX)
微服务项目 每个项目都有单独的网关配置和端口号 希望能加入一个配置功能 可以自动读取Spring Gateway的配置文件 实现网关自动路由
或者给个配置地方也行 
<img width="609" alt="image" src="https://user-images.githubusercontent.com/28811199/174555254-15c8a2eb-cfe9-4545-9360-34b3001f657a.png">
类似配置如下
   routes: #路由数组
        #用户中心路由
        - id: mall-user #当前路由的标识，唯一，默认是UUID
          uri: lb://mall-user #请求转发后的最终地址
          order: 1 #路由的优先级，数字越小的优先级越高
          predicates: #断言，条件判断
            - Path=/api/user/**
          filters: #过滤器，对请求的URI做处理
            - StripPrefix=2 # 0表示不对URI做处理，1表示在请求转发之前去掉第一层路径 2 去掉两层 =/api/user/
        #认证中心
        - id: mall-oauth
          uri: lb://mall-oauth
          order: 1
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=2
        #系统服务
        - id: mall-platform
          uri: lb://mall-platform
          order: 1
          predicates:
            - Path=/api/platform/**
          filters:
            - StripPrefix=2
        #推荐服务
        - id: mall-platform
          uri: lb://mall-recommend
          order: 1
          predicates:
            - Path=/api/recommend/**
          filters:
            - StripPrefix=2
        #商家服务
        - id: mall-business
          uri: lb://mall-business
          order: 1
          predicates:
           - Path=/api/business/**
          filters:
            - StripPrefix=2
        #商品服务
        - id: mall-goods
          uri: lb://mall-goods
          order: 1
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix=2
        #购物车
        - id: mall-shopcar
          uri: lb://mall-shopcar
          order: 1
          predicates:
            - Path=/api/shopcar/**
          filters:
            - StripPrefix=2
        #消息模块
        - id: mall-msg
          uri: lb://mall-msg
          order: 1
          predicates:
            - Path=/api/msg/**
          filters:
            - StripPrefix=2
        #物流模块
        - id: mall-logistics
          uri: lb://mall-logistics
          order: 1
          predicates:
            - Path=/api/logistics/**
          filters:
            - StripPrefix=2
        #订单模块
        - id: mall-order
          uri: lb://mall-order
          order: 1
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
        #支付模块
        - id: mall-pay
          uri: lb://mall-pay
          order: 1
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=2

**Comment by kings1990** [comment]
The next version(2023.1.1+) supports quickly adding domain from Yml or Properties config

中文：下个版本(2023.1.1+)支持从项目配置文件快速添加配置

**Comment by kings1990** [comment]
Please upgrade to 2023.1.1+

Document: https://dromara.gitee.io/fast-request/guide/features/projectLevelDomainConfig.html
