### ISSUE TITLE
不支持controller的组合注解

### ISSUE THREAD

**Issue by pig56** [dromara/fast-request#99]
![image](https://user-images.githubusercontent.com/38535244/179802218-a4a8b616-3a47-41d6-9aff-bf576d8756eb.png)
![image](https://user-images.githubusercontent.com/38535244/179802349-b527c438-e83f-4148-87c0-9b254d7838f6.png)
controller上非@RequestMapping注解不支持，此处用了自定义注解组合多个注解没有小火箭，也不能获得正确的url前缀

**Comment by kings1990** [comment]
自定义注解暂不支持，玩法太多了

**Comment by pig56** [comment]
> 自定义注解暂不支持，安排过多

无论哪个自定义注解，头上都会带@RequestMapping的吧可以定位到该注解的呀

**Comment by pig56** [comment]
> 自定义注解暂不支持，玩法太多了

对不起，好像不好定位

**Comment by pig56** [comment]
> 自定义注解暂不支持，玩法太多了

AnnotatedElementUtils.findAllMergedAnnotations用spring方法可以找到组件头上是否有RequestMapping注解，即使不是直接注解，比心.jpg

**Comment by kings1990** [comment]
插件 即 非运行时，所有的内容全是字符串 不能用这种特殊的方法

**Comment by kings1990** [comment]
2024.1.7 加入支持
